language: ruby
rvm:
  - "2.2.1"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - bundle install
  - npm install -g bower gulp coffee-script
  - npm install
  - bower install
  - gulp build
script: export DISPLAY=:99.0 && bundle exec rspec spec
